version: '3.8'
services:
  sql-service:
    build:
      context: .
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=Alma2023@
      - ACCEPT_EULA=Y
      - MSSQL_DATA_DIR=/var/opt/sqlserver/data
      - MSSQL_LOG_DIR=/var/opt/sqlserver/log
      - MSSQL_BACKUP_DIR=/var/opt/sqlserver/backup
    volumes:
      - ./db/ini.sql:/docker-entrypoint-initdb.d/ini.sql